#!/bin/bash
#
# This is not safe re. race conditions,
# but we assume the dispatcher to deal with serialization.
#

if [ -f /tmp/data-probe-$1-pidfile ]
then
	pid=`cat /tmp/data-probe-$1-pidfile`
	rm /tmp/data-probe-$1-pidfile
	kill -2 $pid && sleep 2
fi

if [ -f /tmp/data-probe-$1 ]
then
	sync
	mv /tmp/data-probe-$1 /tmp/data-probe-$1_old
	cat /tmp/data-probe-$1_old
fi

if [ -f /tmp/gnuplot-$1 ]
then
	gnuplot /tmp/gnuplot-$1
fi


uuid=`echo $2 | cut -d "-" -f1` 

mkdir $uuid
cp $2 $uuid

rsync -r $uuid powerci@powerci.org:/var/www/html/kernel-ci/attachments
