#!/bin/bash
#
# This is not safe re. race conditions,
# but we assume the dispatcher to deal with serialization.
#
## ABI:
#
# arg1 : probe number
# arg2 : filename for attached data contents

if [ -f /tmp/pidfile-$1 ]
then
	pid=`cat /tmp/pidfile-$1`
	rm /tmp/pidfile-$1
	kill -2 $pid && sleep 2
fi

if [ -f /tmp/stats-$1 ]
then
	sync
	mv /tmp/stats-$1 /tmp/stats-$1_old
	cat /tmp/stats-$1_old
fi

if [ -f /tmp/gnuplot-$1 ]
then
	gnuplot /tmp/gnuplot-$1
fi

uuid=`basename $2` 

mkdir /tmp/$uuid

# put the time stamps as the first column for the plotting widget in powerci
cat $2 | awk 'BEGIN {FS=OFS=","}{t=$1;$1=$5;$5=t;print}' > /tmp/$uuid/data.csv

rsync -r /tmp/$uuid powerci@powerci.org:/var/www/html/kernel-ci/attachments
